QLKhachSan/Controllers/RoomController.cs
using Microsoft.AspNetCore.Mvc;
using QLKhachSan.Models;
using QLKhachSan.ViewModels;
using QLKhachSan.Helpers;
using Microsoft.AspNetCore.Authorization;
using System.Net.Mail;
using System.Net;
using QLKhachSan.Services;
using Newtonsoft.Json;
using System.Globalization;
using Microsoft.AspNetCore.SignalR;
using QLKhachSan.SignalRChat;
using System;
using X.PagedList;

namespace QLKhachSan.Controllers
{
    public class RoomController : Controller
    {
        private readonly ILogger<RoomController> _logger;
        private readonly QLKhachSanTTTNContext db;
        private readonly IVnPayService _vnPayService;
        private readonly IHubContext<ChatHub> _hubContext;
        public RoomController(ILogger<RoomController> logger, QLKhachSanTTTNContext context, IVnPayService vnPayService, IHubContext<ChatHub> hubContext)
        {
            _logger = logger;
            db = context;
            _vnPayService = vnPayService;
            _hubContext = hubContext;
        }
        public List<BookingVM> Cart => HttpContext.Session.Get<List<BookingVM>>("Cart") ?? new List<BookingVM>();
        #region Đặt phòng
        public IActionResult AddRoomToBooking(BookingVM model)
        {
            var selectedRoomsJson = HttpContext.Session.GetString("SelectedRooms");
            var selectedRooms = new List<BookingVM>();

            // Kiểm tra nếu có danh sách phòng đã chọn trong session
            if (!string.IsNullOrEmpty(selectedRoomsJson))
            {
                selectedRooms = JsonConvert.DeserializeObject<List<BookingVM>>(selectedRoomsJson);
            }
            if(model.ngayden == null || model.ngaydi == null || model.songuoitoida == null)
            {
                return Json(new { success = false, message = "Hãy chọn thông tin đặt phòng" });
            }
            // Thêm phòng mới vào danh sách (dùng List<int> cho mã phòng)
            selectedRooms.Add(new BookingVM
            {
                maphong = new List<int> { model.maphong.First() }, // Thêm một mã phòng
                tenphong= model.tenphong,
                ngayden = model.ngayden,
                ngaydi = model.ngaydi,
                songuoitoida = model.songuoitoida
            });

            // Cập nhật lại session
            HttpContext.Session.SetString("SelectedRooms", JsonConvert.SerializeObject(selectedRooms));

            return Json(new { success = true, message = "Phòng đã được thêm vào danh sách đặt phòng!" });
        }

        //[Authorize]
        public IActionResult Booking()
        {
            var email = HttpContext.Session.GetString("email");
            if (email != null)
            {
                var khachhang = (from kh in db.KhachHangs
                                 where kh.Email == email
                                 select kh).FirstOrDefault();
                ViewBag.email = khachhang.Email;
                ViewBag.diachi = khachhang.DiaChi;
                ViewBag.sdt = khachhang.Sdt;
            }

            // Lấy danh sách phòng từ session
            var selectedRoomsJson = HttpContext.Session.GetString("SelectedRooms");
            if (string.IsNullOrEmpty(selectedRoomsJson))
            {
                ModelState.AddModelError("", "Chưa có phòng nào được chọn.");
                return View();
            }

            var selectedRooms = JsonConvert.DeserializeObject<List<BookingVM>>(selectedRoomsJson);
            double totalAmount = 0;

            foreach (var room in selectedRooms)
            {
                foreach (var maphong in room.maphong)
                {
                    var gia = (from lp in db.LoaiPhongs
                               join p in db.Phongs on lp.MaLp equals p.MaLp
                               where p.MaPhong == maphong
                               select lp.Gia).FirstOrDefault();

                    // Kiểm tra giá phòng
                    if (gia == null)
                    {
                        ModelState.AddModelError("", $"Không tìm thấy giá phòng cho mã phòng {maphong}.");
                        return View(selectedRooms);
                    }

                    // Tính số ngày ở
                    if (room.ngaydi != null && room.ngayden != null)
                    {
                        TimeSpan soNgay = room.ngaydi - room.ngayden;
                        int soNgayTrongKhoang = soNgay.Days + 1;

                        if (soNgayTrongKhoang <= 0)
                        {
                            ModelState.AddModelError("", "Ngày đi phải lớn hơn ngày đến.");
                            return View(selectedRooms);
                        }
                        room.thanhtien = (double)gia * soNgayTrongKhoang;
                        totalAmount += room.thanhtien; // Cộng dồn vào tổng tiền
                    }
                    else
                    {
                        ModelState.AddModelError("", "Ngày đến hoặc ngày đi không hợp lệ.");
                        return View(selectedRooms);
                    }
                }
            }

            // Gán tổng tiền và thông tin phòng đã chọn vào model
            ViewBag.TotalAmount = totalAmount;
            ViewBag.SelectedRooms = selectedRooms;

            

            return View(selectedRooms);
        }
        #endregion

        #region Lưu phòng được đặt vào db
        public void SaveBookingInfoToDatabase(int customerID, BookingVM model, int roomID, string payment)
        {
            var khachhang = db.KhachHangs.SingleOrDefault(kh => kh.MaKh == customerID);
            var khachhang1 = db.KhachHangs.SingleOrDefault(kh => kh.Email == model.Email);

            if (khachhang != null)
            {
                var hoadon = new HoaDon
                {
                    MaKh = customerID,
                    NgayThanhToan = DateTime.Now,
                    TenKh = model.GiongKhachHang ? khachhang.TenKh : model.HoTen,
                    Email = model.GiongKhachHang ? khachhang.Email : model.Email,
                    Sdt = model.GiongKhachHang ? khachhang.Sdt : model.DienThoai,
                    TinhTrang = payment == "Thanh toán VNPay" ? "Đã thanh toán" : "Đã đặt cọc"

                };
                db.Add(hoadon);
                db.SaveChanges();
                var datphong = new DatPhong
                {
                    SoHoaDon = hoadon.SoHoaDon,
                    MaPhong = roomID,
                    NgayDen = model.ngayden,
                    NgayDi = model.ngaydi,
                    SoNguoi = model.songuoitoida,
                    IsDelete = 0
                };
                db.Add(datphong);
                db.SaveChanges();
            }
            else
            {
                var hoadon = new HoaDon
                {
                    MaKh = null,
                    NgayThanhToan = DateTime.Now,
                    TenKh = model.GiongKhachHang ? khachhang.TenKh : model.HoTen,
                    Email = model.GiongKhachHang ? khachhang.Email : model.Email,
                    Sdt = model.GiongKhachHang ? khachhang.Sdt : model.DienThoai,
                    TinhTrang = payment == "Thanh toán VNPay" ? "Đã thanh toán" : "Đã đặt cọc"

                };
                db.Add(hoadon);
                db.SaveChanges();
                var datphong = new DatPhong
                {
                    SoHoaDon = hoadon.SoHoaDon,
                    MaPhong = roomID,
                    NgayDen = model.ngayden,
                    NgayDi = model.ngaydi,
                    SoNguoi = model.songuoitoida,
                    IsDelete = 0
                };
                db.Add(datphong);
                db.SaveChanges();
            }
        }
        #endregion

        #region Gửi email thông tin đã đặt phòng cho khách hàng
        private void SendConfirmationEmail(List<BookingVM> bookingModels, string customerEmail, string paymentMethod)
        {
            string subject;
            string paymentInfo;

            var strSanPham = $@"
<table style='border-collapse: collapse; width: 100%;'>
    <thead>
        <tr style='background-color: #f2f2f2;'>
            <th style='border: 1px solid #ddd; padding: 8px;'>Tên khách sạn</th>
            <th style='border: 1px solid #ddd; padding: 8px;'>Tên phòng</th>
            <th style='border: 1px solid #ddd; padding: 8px;'>Ngày đến</th>
            <th style='border: 1px solid #ddd; padding: 8px;'>Ngày đi</th>
            <th style='border: 1px solid #ddd; padding: 8px;'>Số người</th>
            <th style='border: 1px solid #ddd; padding: 8px;'>Địa chỉ</th>";

            if (paymentMethod == "Đặt cọc phòng(40%)")
            {
                strSanPham += "<th style='border: 1px solid #ddd; padding: 8px;'>Tiền cọc</th><th style='border: 1px solid #ddd; padding: 8px;'>Cần thanh toán</th>";
            }
            else
            {
                strSanPham += "<th style='border: 1px solid #ddd; padding: 8px;'>Tổng tiền</th>";
            }
            strSanPham += @"
        </tr>
    </thead>
    <tbody>";

            foreach (var bookingModel in bookingModels)
            {
                foreach (var maphong in bookingModel.maphong)
                {
                    var tenks = (from ks in db.KhachSans
                                 join lp in db.LoaiPhongs on ks.MaKs equals lp.MaKs
                                 join p in db.Phongs on lp.MaLp equals p.MaLp
                                 where p.MaPhong == maphong
                                 select ks.TenKhachSan).FirstOrDefault();
                    var diachi = (from ks in db.KhachSans
                                  join lp in db.LoaiPhongs on ks.MaKs equals lp.MaKs
                                  join p in db.Phongs on lp.MaLp equals p.MaLp
                                  where p.MaPhong == maphong
                                  select ks.DiaChi).FirstOrDefault();

                    strSanPham += $@"
        <tr>

QLKhachSan/Views/Room/Booking.cshtml
@inject IHttpContextAccessor HttpContextAccessor
@model List<QLKhachSan.ViewModels.BookingVM>

@{
    ViewData["Title"] = "Booking";
    Layout = "_LayoutCheckOut";
}
<div class="container">
    <nav class="breadcrumb-nav d-flex align-items-center" aria-label="breadcrumb">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a class="under" href="index.html">Trang chủ</a></li>
                <li class="breadcrumb-item active" aria-current="page"><span>Thông tin đặt phòng</span></li>
            </ol>
        </div>
    </nav>
    <div class="row">
    <aside class="sidebar col-lg-3 order-1 order-lg-0">
        <div class="sidebar__content js-sticky-top">
            <section class="sidebar__card card">
                <ul class="sidebar__payment">
                    @if (Model != null && Model.Count() > 0 )
                    {
                        foreach (var room in Model)
                        {
                            <li class="d-inline-block align-top mr-5 mb-2">
                                <div class="fw-bold">Tên phòng</div>
                                <ul>
                                    <li>- @room.tenphong</li>
                                </ul>
                            </li>
                            <li class="d-inline-block align-top mr-5 mb-2">
                                <div class="fw-bold">Ngày đến</div>
                                <ul>
                                    <li>- @room.ngayden.ToString("dd/MM/yyyy")</li>
                                </ul>
                            </li>
                            <li class="d-inline-block align-top mr-5 mb-2">
                                <div class="fw-bold">Ngày đi</div>
                                <ul>
                                    <li>- @room.ngaydi.ToString("dd/MM/yyyy")</li>
                                </ul>
                            </li>
                        }
                    }
                    else
                    {
                        <li>Không có phòng nào được chọn.</li>
                    }
                </ul>
                <hr class="mt-2">
                <ul class="sidebar__payment-total">
                    <li class="h4 fw-bold f-primary mb-0">Tổng tiền: @ViewBag.TotalAmount €</li>
                </ul>
            </section>
            <section class="sidebar__card card">
                <div class="sidebar__card-title">
                    <h4 class="card-title mb-1">Cần trợ giúp đặt chỗ?</h4>
                    <hr class="my-3 mt-2" />
                </div>
                <p>Hãy gọi cho nhóm dịch vụ khách hàng của chúng tôi theo số bên dưới để nói chuyện với một trong những cố vấn của chúng tôi, người sẽ giúp bạn đáp ứng mọi nhu cầu trong kỳ nghỉ của bạn.</p>
                <ul class="sidebar__contacts">
                    <li class="d-flex align-items-center"><i class="icon icon-phone mr-2"></i><a class="fw-bold" href="tel:#">0903888888</a></li>
                </ul>
            </section>
        </div>
    </aside>

        <div class="col-lg-9 d-flex" id="barba-wrapper">
    <div class="barba-container">
        <div class="booking-card card">
            <div class="card-body">
                <div class="booking-card__title">
                    <h2>Thông tin khách hàng</h2>
                    <hr class="mb-4">
                </div>
                <form style="width:820px;" class="booking-card__form" asp-controller="Room" asp-action="ConfirmBooking" method="post" id="bookingForm">
                    <div class="row pad-lg-20">
                        <input type="hidden" name="totalAmount" value="@ViewBag.TotalAmount" />
                        @foreach (var room in Model) // Lặp qua từng phòng trong danh sách
                        {
                           <input type="hidden" name="maphong" value="@string.Join(",", room.maphong)" />
                            <input type="hidden" name="ngayden" value="@room.ngayden" />
                            <input type="hidden" name="ngaydi" value="@room.ngaydi" />
                            <input type="hidden" name="songuoitoida" value="@room.songuoitoida" />
                            <input type="hidden" name="tenphong" value="@room.tenphong" />
                            <input type="hidden" name="thanhtien" value="@room.thanhtien" />
                           
                        };
                        @{
                         var email = HttpContextAccessor.HttpContext.Session.GetString("email");
                        }
                            @if (email != null)
                            {
                                if (ViewBag.email != null || ViewBag.diachi != null || ViewBag.sdt != null)
                                {
                                    <div style="margin-left:20px;" class="form-group col-12">
                                        <input class="form-check-input" name="GiongKhachHang" type="checkbox" id="GiongKhachHang" value="false">
                                        <label class="form-check-label" for="GiongKhachHang">Giống thông tin khách hàng?</label>
                                    </div>
                                    <div class="form-group col-12">
                                        <input class="form-control info" type="text" name="HoTen" placeholder="Họ tên" value="@ViewBag.hoTen" required />
                                        <div class="help-block with-errors"></div>
                                    </div>
                                    <div class="form-group col-12">
                                        <input class="form-control info" id="email" type="email" name="Email" placeholder="Email" value="@ViewBag.email" required />
                                        <div class="help-block with-errors"></div>
                                    </div>
                                    <div class="form-group col-12">
                                        <input class="form-control info" type="text" name="DienThoai" placeholder="Số điện thoại" value="@ViewBag.sdt" required />
                                        <div class="help-block with-errors"></div>
                                    </div>
                                }
                            }
                            else
                            {
                                <div class="form-group col-12">
                                    <input class="form-control info" type="text" name="HoTen" required placeholder="Họ tên" />
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="form-group col-12">
                                    <input class="form-control info" id="email" type="email" name="Email" required placeholder="Email" />
                                    <div class="help-block with-errors"></div>
                                </div>
                                <div class="form-group col-12">
                                    <input class="form-control info" type="text" name="DienThoai" required placeholder="Số điện thoại" />
                                    <div class="help-block with-errors"></div>
                                </div>
                            }
                    </div>
                    <div class="d-flex">
                        <input class="btn btn-secondary btn--round mx-auto ml-sm-0" type="submit" name="payment" value="Đặt cọc phòng(40%)" />
                        <input class="btn btn-secondary btn--round mx-auto ml-sm-0" type="submit" name="payment" value="Thanh toán VNPay" />
                    </div>
                </form>
            </div>
        </div

    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#GiongKhachHang").change(function () {
                if ($(this).prop("checked")) {
                    $(this).val(true);
                    $(".info").addClass("d-none");
                } else {
                    $(this).val(false);
                    $(".info").removeClass("d-none");
                }
            });

            $("#bookingForm").submit(function (event) {
                var hoTen = $('input[name="HoTen"]').val().trim();
                var email = $('input[name="Email"]').val().trim();
                var dienThoai = $('input[name="DienThoai"]').val().trim();
                var giongKhachHang = $('input[name="GiongKhachHang"]').prop('checked');

                // Nếu checkbox "Giống thông tin khách hàng" được chọn, không cần kiểm tra các trường dữ liệu khách hàng
                if (giongKhachHang) {
                    return true;  // cho phép submit form
                }

                var phonePattern = /^0\d{9}$/;
                if (!phonePattern.test(dienThoai)) {
                    alert("Vui lòng nhập số điện thoại hợp lệ (bắt đầu bằng số 0 và có tổng cộng 10 số).");
                    event.preventDefault(); // Ngăn không cho submit form
                    return false;
                }
                return true; // cho phép submit form nếu tất cả kiểm tra đều hợp lệ
            });
        });
    </script>
}

QLKhachSan/Views/Room/ConfirmBooking.cshtml
@model List<QLKhachSan.ViewModels.BookingVM>
@{
    ViewData["Title"] = "ConfirmBooking";
    Layout = "_LayoutCheckOut";
}
<div class="container">
    <nav class="breadcrumb-nav d-flex align-items-center" aria-label="breadcrumb">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a class="under" href="index.html">Trang chủ</a></li>
                <li class="breadcrumb-item active" aria-current="page"><span>Xác nhận thông tin đặt phòng</span></li>
            </ol>
        </div>
    </nav>
    <div class="row">
        <aside class="sidebar col-lg-3 order-1 order-lg-0">
            <div class="sidebar__content js-sticky-top">
                <section class="sidebar__card card">
                    <h4 class="card-title mb-1">Thông tin đặt phòng</h4>
                    <hr class="mt-2">
                    <ul class="sidebar__payment">
                        @foreach (var booking in Model)
                        {
                            <li class="d-inline-block align-top mr-5 mb-2">
                                <div class="fw-bold">Tên phòng:</div>
                                <ul>
                                    <li>- @booking.tenphong</li>
                                </ul>
                            </li>
                            <li class="d-inline-block align-top mr-5 mb-2">
                                <div class="fw-bold">Ngày đến:</div>
                                <ul>
                                    <li>- @booking.ngayden.ToString("dd/MM/yyyy")</li>
                                </ul>
                            </li>
                            <li class="d-inline-block align-top mr-5 mb-2">
                                <div class="fw-bold">Ngày đi:</div>
                                <ul>
                                    <li>- @booking.ngaydi.ToString("dd/MM/yyyy")</li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <hr class="mt-2">
                    <ul class="sidebar__payment-total">
                        <li class="h4 fw-bold f-primary mb-0">Tổng tiền: @Model.Sum(b => b.thanhtien) VND</li>
                    </ul>
                </section>
            </div>
        </aside>
        <div class="col-lg-9 d-flex" id="barba-wrapper">
            <div class="barba-container">
                <div class="booking-card card">
                    <div class="card-body">
                        <div class="booking-card__title">
                            <h2>Xác nhận đặt phòng</h2>
                            <hr class="mb-4">
                        </div>
                        <div class="d-flex flex-wrap align-items-center mb-4">
                            <p class="mark bg-primary-light mb-3">Cảm ơn. Việc đặt chỗ của bạn hiện đã được xác nhận. Vui lòng kiểm tra email của bạn để xem thông tin đặt phòng.</p>
                        </div>
                        <section class="mb-5">
                            <h4>Thông tin khách hàng</h4>
                            <div class="row">
                                <div class="col-12 col-md-8">
                                    <ul class="booking-card__checklist">
                                        <li class="d-flex justify-content-between flex-wrap flex-column flex-sm-row mb-3">
                                            <div class="fw-sm">Số điện thoại:</div><span>@Model.First().DienThoai</span>
                                        </li>
                                        <li class="d-flex justify-content-between flex-wrap flex-column flex-sm-row mb-3">
                                            <div class="fw-sm">Họ tên:</div><span>@Model.First().HoTen</span>
                                        </li>
                                        <li class="d-flex justify-content-between flex-wrap flex-column flex-sm-row mb-3">
                                            <div class="fw-sm">E-mail:</div><span>@Model.First().Email</span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </section>
                        <section class="mb-5">
                            <h4>Thanh toán</h4>
                            <p>Bây giờ bạn đã xác nhận và đảm bảo đặt phòng của mình bằng thẻ tín dụng. Tất cả các khoản thanh toán sẽ được thực hiện tại khách sạn trong thời gian lưu trú của bạn, trừ khi có quy định khác trong chính sách khách sạn hoặc trong điều kiện phòng. Xin lưu ý rằng thẻ tín dụng của bạn có thể được ủy quyền trước đến khi bạn đến.</p>
                        </section>
                        <div class="mb-5">
                            <div class="fw-bold">Khách sạn này chấp nhận các hình thức thanh toán sau:</div>
                            <ul>
                                <li>Thẻ ngân hàng, thẻ tín dụng, tiền mặt</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

QLKhachSan/Views/Room/PaymentFail.cshtml
@{
    ViewData["Title"] = "PaymentFail";
}

<h1>PaymentFail</h1>

QLKhachSan/Views/Room/Success.cshtml
@{
    ViewData["Title"] = "Success";
}

<h1>Success</h1>