QLKhachSan/Models/HoaDon.cs
using System;
using System.Collections.Generic;

namespace QLKhachSan.Models
{
    public partial class HoaDon
    {
        public HoaDon()
        {
            DatPhongs = new HashSet<DatPhong>();
        }

        public int SoHoaDon { get; set; }
        public int? MaKh { get; set; }
        public DateTime? NgayThanhToan { get; set; }
        public DateTime? NgayTao { get; set; }
        public string? TenKh { get; set; }
        public string? Email { get; set; }
        public string? Sdt { get; set; }
        public string? TinhTrang { get; set; }

        public virtual KhachHang? MaKhNavigation { get; set; }
        public virtual ICollection<DatPhong> DatPhongs { get; set; }
    }
}

QLKhachSan/Areas/Admin/Controllers/HoaDonAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QLKhachSan.Models;
using QLKhachSan.ViewModels;
using QLKhachSan.ViewModels.Admin;
using X.PagedList;

namespace QLKhachSan.Areas.Admin.Controllers
{
    [Area("admin")]
    [Authorize(Roles = "Admin")]
    public class HoaDonAdminController : Controller
    {
        QLKhachSanTTTNContext db = new QLKhachSanTTTNContext();
		#region Hóa đơn
		[Route("hoadon")]
        public IActionResult HoaDon(int?maks, int? page)
        {
            int pageSize = 8;
            int pageNumber = page == null || page < 0 ? 1 : page.Value;
            var hoadon = (from hd in db.HoaDons
						  join dp in db.DatPhongs on hd.SoHoaDon equals dp.SoHoaDon
						  join p in db.Phongs on dp.MaPhong equals p.MaPhong
						  join lp in db.LoaiPhongs on p.MaLp equals lp.MaLp
						  join ks in db.KhachSans on lp.MaKs equals ks.MaKs
						  where ks.MaKs == maks
						  select new HoaDonVM
                            {
                                sohoadon = hd.SoHoaDon,
                                tenphong = p.TenPhong,
                                ngaythanhtoan = hd.NgayThanhToan,
                                ngayden = dp.NgayDen,
                                ngaydi = dp.NgayDi,
                                tenkh = hd.TenKh,
                                songuoi = dp.SoNguoi,
                                sdt = hd.Sdt,
                                tinhtrang = hd.TinhTrang
                            }).OrderBy(x => x.sohoadon);
			var khachsan = (from ks in db.KhachSans
							join kh in db.KhachHangs on ks.IdnguoiTao equals kh.MaKh
							select new { ks.MaKs, ks.TenKhachSan }).ToList();
			ViewBag.ks = khachsan;
			ViewBag.MaKS = maks;
			PagedList<HoaDonVM> lst = new PagedList<HoaDonVM>(hoadon, pageNumber, pageSize);

            return View(lst);
        }

        [Route("SuaHD")]
        [HttpGet]
        public IActionResult SuaHD(int id)
        {
            var hoadon = (from hd in db.HoaDons
                          join dp in db.DatPhongs on hd.SoHoaDon equals dp.SoHoaDon
                          join p in db.Phongs on dp.MaPhong equals p.MaPhong
                          where hd.SoHoaDon == id
                          select new HoaDonVM
                          {
                              sohoadon = hd.SoHoaDon,
                              maphong = p.MaPhong,
                              tenphong = p.TenPhong,
                              ngaythanhtoan = hd.NgayThanhToan,
                              ngayden = dp.NgayDen,
                              ngaydi = dp.NgayDi,
                              tenkh = hd.TenKh,
                              songuoi = dp.SoNguoi,
                              sdt = hd.Sdt,
                              tinhtrang = hd.TinhTrang
                          }).FirstOrDefault();
            return View(hoadon);
        }
        [Route("SuaHD")]
        [HttpPost]
        public IActionResult SuaHD(HoaDonVM model)
        {
            var hoadon = db.HoaDons.FirstOrDefault(p => p.SoHoaDon == model.sohoadon);
            if (hoadon != null)
            {
                hoadon.NgayThanhToan = model.ngaythanhtoan;
                hoadon.TenKh = model.tenkh;
                hoadon.Sdt = model.sdt;
                hoadon.TinhTrang = model.tinhtrang;

                db.Update(hoadon);

                var dp = db.DatPhongs.FirstOrDefault(p => p.SoHoaDon == model.sohoadon);
                if (dp != null)
                {
                    dp.NgayDen = model.ngayden;
                    dp.NgayDi = model.ngaydi;
                    dp.SoNguoi = model.songuoi;

                    db.Update(dp);
                }

                db.SaveChanges();
                TempData["Message"] = "Cập nhật hóa đơn thành công!";
                return RedirectToAction("HoaDon");
            }
            return View();
        }
		[Route("timkiemhoadon")]
		public IActionResult TimKiemHoaDon(int maks,string searchTerm, int? page)
		{
			int pageSize = 8;
			int pageNumber = page ?? 1;

			var hoadonQuery = from hd in db.HoaDons
							  join dp in db.DatPhongs on hd.SoHoaDon equals dp.SoHoaDon
							  join p in db.Phongs on dp.MaPhong equals p.MaPhong
							  join lp in db.LoaiPhongs on p.MaLp equals lp.MaLp
							  join ks in db.KhachSans on lp.MaKs equals ks.MaKs
                              where ks.MaKs == maks
							  select new HoaDonVM
							  {
								  sohoadon = hd.SoHoaDon,
								  tenphong = p.TenPhong,
								  ngaythanhtoan = hd.NgayThanhToan,
								  ngayden = dp.NgayDen,
								  ngaydi = dp.NgayDi,
								  tenkh = hd.TenKh,
								  songuoi = dp.SoNguoi,
								  sdt = hd.Sdt,
								  tinhtrang = hd.TinhTrang
							  };

			if (!string.IsNullOrEmpty(searchTerm))
			{
				hoadonQuery = hoadonQuery.Where(hd => hd.sohoadon.ToString().Contains(searchTerm)
												   || hd.tenphong.Contains(searchTerm)
												   || hd.tenkh.Contains(searchTerm)
												   || hd.sdt.Contains(searchTerm)
												   || hd.tinhtrang.Contains(searchTerm));
			}

			var hoadonList = hoadonQuery.OrderBy(x => x.sohoadon).ToPagedList(pageNumber, pageSize);
			var khachsan = (from ks in db.KhachSans
							join kh in db.KhachHangs on ks.IdnguoiTao equals kh.MaKh
							select new { ks.MaKs, ks.TenKhachSan }).ToList();
			ViewBag.ks = khachsan;
			ViewBag.MaKS = maks;
			ViewBag.SearchTerm = searchTerm;
			return View(hoadonList);
		}
		#endregion

	}
}

QLKhachSan/Areas/Admin/Controllers/HoaDonController.cs
using Microsoft.AspNetCore.Mvc;
using QLKhachSan.Models;

namespace QLKhachSan.Areas.Admin.Controllers
{
    [Area("admin")]
    public class HoaDonController : Controller
    {
        QLKhachSanTTTNContext db = new QLKhachSanTTTNContext();
        [Route("hoadon")]
        public IActionResult HoaDon()
        {
            return View();
        }
    }
}

QLKhachSan/Areas/Admin/Views/HoaDonAdmin/HoaDon.cshtml
@using QLKhachSan.ViewModels.Admin;
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<HoaDonVM>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "HoaDon";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="row">
	<div class="col-xl-12">
		<div class="d-flex mb-4 justify-content-between align-items-center flex-wrap">
			<div class="card-tabs mt-3 mt-sm-0 mb-xxl-0 mb-4">
				<ul class="nav nav-tabs" role="tablist">
					<li class="nav-item">
						<a class="nav-link active" data-bs-toggle="tab"  role="tab">Hóa đơn </a>
					</li>
				</ul>
			</div>
			<div>
				<select class="form-control" id="selectedHotel">
					<option value="" selected>Chọn khách sạn</option>
					@foreach (var khachsan in ViewBag.ks)
					{
						<option value="@khachsan.MaKs">@khachsan.TenKhachSan</option>
					}
				</select>
			</div>
			<div class="table-search">
				<div style="border-bottom-left-radius: 1.375rem;" class="input-group search-area mb-xxl-0 mb-4">
					<form asp-action="TimKiemHoaDon" method="get" class="d-flex">
						<input type="hidden" name="maks" value="@ViewBag.MaKS" />
						<input style="height:auto" type="text" name="searchTerm" class="form-control" placeholder="Nhập thông tin .." value="@ViewBag.SearchTerm">
						<button type="submit" class="input-group-text btn btn-primary"><i class="flaticon-381-search-2"></i></button>
					</form>
				</div>
			</div>
@* 			<a asp-action="ThemLP" class="btn btn-primary mb-xxl-0 mb-4 radius-btn"><i class="far fa-file-word me-2"></i>Create Bill</a> *@
		</div>
		<div class="tab-content">
			<div class="tab-pane active show" id="All">
				<div class="text-danger">@TempData["Message"]</div>
				<div class="table-responsive">
					<table class="table table-bordered table-striped check-data  display mb-4 dataTablesCard booking-table room-list-tbl table-responsive-lg " id="guestTable-all">
						<thead>
							<tr>
								<th>Số HD</th>
								<th>Tên phòng</th>
								<th>Ngày thanh toán</th>
								<th>Ngày đến</th>
								<th>Ngày đi</th>
								<th>Tên KH</th>
								<th>Số người</th>
								<th>SDT</th>
								<th>Tình trạng</th>
								<th style="text-align:center;">Chức năng</th>
							</tr>
						</thead>
						<tbody>
							@foreach (var item in Model)
							{
								<tr>
									<td>
										<div>
											<span class="fs-16">@item.sohoadon</span>
										</div>
									</td>
									<td>
										<div>
											<span class="fs-16">@item.tenphong</span>
										</div>
									</td>
									<td>
										<div>
											<span class="fs-16">@item.ngaythanhtoan</span>
										</div>
									</td>
									<td>
										<div>
											<span class="fs-16">@item.ngayden</span>
										</div>
									</td>
									<td>
										<div>
											<span class="fs-16">@item.ngaydi</span>
										</div>
									</td>
									<td>
										<div>
											<span class="fs-16">@item.tenkh</span>
										</div>
									</td>
									<td>
										<div>
											<span class="fs-16">@item.songuoi</span>
										</div>
									</td>
									<td>
										<div>
											<span class="fs-16">@item.sdt</span>
										</div>
									</td>
									<td>
										<div>
											<span class="fs-16">@item.tinhtrang</span>
										</div>
									</td>
									<td class="text-center">
										<a class="btn btn-sm btn-warning mx-1" asp-controller="HoaDonAdmin" asp-action="SuaHD" asp-route-id="@item.sohoadon">
											<i class="far fa-edit"></i> Edit
										</a>
										<a class="btn btn-sm btn-danger mx-1" onclick="return confirm('Bạn có chắc chắn muốn xóa phòng này không?')" asp-controller="HoaDonAdmin" asp-action="XoaHD" asp-route-id="@item.sohoadon">
											<i class="far fa-trash-alt"></i> Delete
										</a>
									</td>
								</tr>
							}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div style="margin: 0 auto">
	@Html.PagedListPager(Model, page => Url.Action("HoaDon", new { maks = ViewBag.MaKS, page = page }), new X.PagedList.Web.Common.PagedListRenderOptions()
{
	LiElementClasses = new List<String> {"page-item"},
	PageClasses = new List<String> {"page-link"}
	})
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="~/LayoutAdmin/public/assets/css/style-admin.css">
<script>
	$(document).ready(function () {
		// Kiểm tra nếu có giá trị đã lưu trong local storage
		var selectedHotelId = localStorage.getItem('HotelId');
		if (selectedHotelId) {
			// Đặt giá trị đã lưu vào dropdown
			$('#selectedHotel').val(selectedHotelId);
			// Clear the local storage after setting the dropdown value
			localStorage.removeItem('HotelId');
		}
	});
</script>
<script>
	$(document).ready(function () {
		// Kiểm tra nếu có giá trị đã lưu trong local storage
		var selectedHotelId = localStorage.getItem('HotelId');
		if (selectedHotelId) {
			// Đặt giá trị đã lưu vào dropdown
			$('#selectedHotel').val(selectedHotelId);
		}

		// Sự kiện khi giá trị của dropdown thay đổi
		$('#selectedHotel').change(function () {
			var selectedHotelId = $(this).val();
			if (selectedHotelId) {
				// Lưu giá trị mới vào local storage
				localStorage.setItem('HotelId', selectedHotelId);
				// Tạo URL mới với giá trị maks và chuyển hướng trang đến URL đó
				var newUrl = '@Url.Action("HoaDon", "HoaDonAdmin")?maks=' + selectedHotelId;
				window.location.href = newUrl;
			}
		});
	});
</script>

QLKhachSan/Areas/Admin/Views/HoaDonAdmin/SuaHD.cshtml
@model QLKhachSan.ViewModels.Admin.HoaDonVM
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "SuaHD";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<h2 style="color: dimgray;" class="text-center mb-4">Cập nhật hóa đơn</h2>
<div class="card-body">
    <div class="basic-form">
        <form method="post" asp-action="SuaHD" enctype="multipart/form-data">
            <div class="text-danger">@TempData["Message"]</div>
            <div class="mb-3">
                <input hidden type="text" class="form-control" name="sohoadon" value="@Model.sohoadon" readonly>
                <input hidden type="text" class="form-control" name="maphong" value="@Model.maphong" readonly>
            </div>
            <div class="mb-3">
                <label class="form-label">Tên phòng<span class="text-danger">(*)</span></label>
                <input asp-for="tenphong" type="text" required class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">Ngày thanh toán<span class="text-danger">(*)</span></label>
                <input asp-for="ngaythanhtoan" type="date" class="form-control" >
            </div>
            <div class="mb-3">
                <label class="form-label">Ngày đến<span class="text-danger">(*)</span></label>
                <input asp-for="ngayden" type="date" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">Ngày đi<span class="text-danger">(*)</span></label>
                <input asp-for="ngaydi" type="date" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">Tên khách hàng<span class="text-danger">(*)</span></label>
                <input asp-for="tenkh" type="text" required class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">Số người<span class="text-danger">(*)</span></label>
                <input asp-for="songuoi" type="text" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">Số điện thoại<span class="text-danger">(*)</span></label>
                <input asp-for="sdt" type="text" required class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">Tình trạng<span class="text-danger">(*)</span> </label>
                <select asp-for="tinhtrang" class="default-select form-control wide mb-3">
                    <option value="Đã thanh toán">Đã thanh toán</option>
                    <option value="Chưa thanh toán">Chưa thanh toán</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary mt-3">Lưu</button>
        </form>
    </div>
</div>

QLKhachSan/Areas/Admin/Views/HoaDonAdmin/TimKiemHoaDon.cshtml
@using QLKhachSan.ViewModels.Admin;
@using X.PagedList.Mvc.Core;
@model X.PagedList.IPagedList<HoaDonVM>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
	ViewData["Title"] = "TimKiemHoaDon";
	Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="row">
	<div class="col-xl-12">
		<div class="d-flex mb-4 justify-content-between align-items-center flex-wrap">
			<div class="card-tabs mt-3 mt-sm-0 mb-xxl-0 mb-4">
				<ul class="nav nav-tabs" role="tablist">
					<li class="nav-item">
						<a class="nav-link active" data-bs-toggle="tab" role="tab">Hóa đơn </a>
					</li>
				</ul>
			</div>
			<div>
				<select class="form-control" id="selectedHotel">
					<option value="" selected>Chọn khách sạn</option>
					@foreach (var khachsan in ViewBag.ks)
					{
						<option value="@khachsan.MaKs">@khachsan.TenKhachSan</option>
					}
				</select>
			</div>
			<div class="table-search">
				<div style="border-bottom-left-radius: 1.375rem;" class="input-group search-area mb-xxl-0 mb-4">
					<form asp-action="TimKiemHoaDon" method="get" class="d-flex">
						<input type="hidden" name="maks" value="@ViewBag.MaKS" />
						<input style="height:auto" type="text" name="searchTerm" class="form-control" placeholder="Nhập thông tin .." value="@ViewBag.SearchTerm">
						<button type="submit" class="input-group-text btn btn-primary"><i class="flaticon-381-search-2"></i></button>
					</form>
				</div>
			</div>
			@* 			<a asp-action="ThemLP" class="btn btn-primary mb-xxl-0 mb-4 radius-btn"><i class="far fa-file-word me-2"></i>Create Bill</a> *@
		</div>
		<div class="tab-content">
			<div class="tab-pane active show" id="All">
				<div class="text-danger">@TempData["Message"]</div>
				<div class="table-responsive">
					<table class="table table-bordered table-striped check-data  display mb-4 dataTablesCard booking-table room-list-tbl table-responsive-lg " id="guestTable-all">
						<thead>
							<tr>
								<th>Số HD</th>
								<th>Tên phòng</th>
								<th>Ngày thanh toán</th>
								<th>Ngày đến</th>
								<th>Ngày đi</th>
								<th>Tên KH</th>
								<th>Số người</th>
								<th>SDT</th>
								<th>Tình trạng</th>
								<th style="text-align:center;">Chức năng</th>
							</tr>
						</thead>
						<tbody>
							@foreach (var item in Model)
							{
								<tr>
									<td>
										<div>
											<span class="fs-16">@item.sohoadon</span>
										</div>
									</td>
									<td>
										<div>
											<span class="fs-16">@item.tenphong</span>
										</div>
									</td>
									<td>
										<div>
											<span class="fs-16">@item.ngaythanhtoan</span>
										</div>
									</td>
									<td>
										<div>
											<span class="fs-16">@item.ngayden</span>
										</div>
									</td>
									<td>
										<div>
											<span class="fs-16">@item.ngaydi</span>
										</div>
									</td>
									<td>
										<div>
											<span class="fs-16">@item.tenkh</span>
										</div>
									</td>
									<td>
										<div>
											<span class="fs-16">@item.songuoi</span>
										</div>
									</td>
									<td>
										<div>
											<span class="fs-16">@item.sdt</span>
										</div>
									</td>
									<td>
										<div>
											<span class="fs-16">@item.tinhtrang</span>
										</div>
									</td>
									<td class="text-center">
										<a class="btn btn-sm btn-warning mx-1" asp-controller="HoaDonAdmin" asp-action="SuaHD" asp-route-id="@item.sohoadon">
											<i class="far fa-edit"></i> Edit
										</a>
										<a class="btn btn-sm btn-danger mx-1" onclick="return confirm('Bạn có chắc chắn muốn xóa phòng này không?')" asp-controller="HoaDonAdmin" asp-action="XoaHD" asp-route-id="@item.sohoadon">
											<i class="far fa-trash-alt"></i> Delete
										</a>
									</td>
								</tr>
							}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div style="margin: 0 auto">
	@Html.PagedListPager(Model, page => Url.Action("TimKiemHoaDon", new { maks = ViewBag.MaKS, page = page, SearchTerm = ViewBag.SearchTerm }), new X.PagedList.Web.Common.PagedListRenderOptions()
{
	LiElementClasses = new List<String> { "page-item" },
	PageClasses = new List<String> { "page-link" }
})
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="~/LayoutAdmin/public/assets/css/style-admin.css">
<script>
	$(document).ready(function () {
		// Kiểm tra nếu có giá trị đã lưu trong local storage
		var selectedHotelId = localStorage.getItem('HotelId');
		if (selectedHotelId) {
			// Đặt giá trị đã lưu vào dropdown
			$('#selectedHotel').val(selectedHotelId);
			// Clear the local storage after setting the dropdown value
			localStorage.removeItem('HotelId');
		}
	});
</script>
<script>
	$(document).ready(function () {
		// Kiểm tra nếu có giá trị đã lưu trong local storage
		var selectedHotelId = localStorage.getItem('HotelId');
		if (selectedHotelId) {
			// Đặt giá trị đã lưu vào dropdown
			$('#selectedHotel').val(selectedHotelId);
		}

		// Sự kiện khi giá trị của dropdown thay đổi
		$('#selectedHotel').change(function () {
			var selectedHotelId = $(this).val();
			if (selectedHotelId) {
				// Lưu giá trị mới vào local storage
				localStorage.setItem('HotelId', selectedHotelId);
				// Tạo URL mới với giá trị maks và chuyển hướng trang đến URL đó
				var newUrl = '@Url.Action("TimKiemHoaDon", "HoaDonAdmin")?maks=' + selectedHotelId + '&searchTerm=' + '@ViewBag.SearchTerm';
				window.location.href = newUrl;
			}
		});
	});
</script>